### PR TITLE
Add a filter to limit tests to only those containing the function name.

### PR DESCRIPTION
**Pull request by ChrisLGardner**
As seen in #12 the Get-FunctionTestCoverage is running the full suite of Pester tests for every function.

I was going to do something fancy with Regex or Ast filtering to check for the function name in each test file when it isn't being used in mocks or text strings but this turned out to be the easier solution.

Running Measure-Command against a module I've got and the running time of the existing module is about 1.5 minutes, using the modified function drops the running time down to ~30 seconds.

It needs the tests updating but I'll add those in the next few days.

### CODE REVIEW

**Comment by ChrisLGardner** [comment]
The AppVeyor build doesn't seem to run due to some problem getting Selenium web driver. I'll get some tests running first and then see if I can figure out what's going on with that.

**Comment by ChrisLGardner** [comment]
I've updated the unit tests a bit. The test which checks if it runs against the source folder when you don't provide a TestsPath value needs a bit of tweaking in line with the other similar tests to ensure it returns a single file rather than the whole folder.

**Comment by ChrisLGardner** [comment]
The build now fails because of a problem with the Coveralls token. @MathieuBuisson want to have a look over this and see what you think of the change?

**Comment by MathieuBuisson** [comment]
Thanks a lot @ChrisLGardner  for this contribution !  

I'm looking into it.

**Comment by MathieuBuisson** [comment]
Hi @ChrisLGardner ,  

I manually merged your change into a separate branch named PR_15 :  
https://github.com/MathieuBuisson/PSCodeHealth/commits/PR_15

As you can guess from the commit messages, I fixed a few issues (mostly unrelated to your change) to ensure all the tests pass.
And they do all pass, now :
https://ci.appveyor.com/project/MathieuBuisson/pscodehealth/build/0.2.23

So I pushed a commit to your pull request branch to sync it to the current state of the PR_15 branch.

**Pull request merged**
